### ISSUE TITLE
Vinto users can turn video on and off as they please

### ISSUE THREAD

**Issue by khu-md** [mohicans-pop-2008/vinto#33]
See also #37 

- [ ] Write a function that toggles the mute for video tracks
  - [ ] Have it be the onClick listener for the <Mute type=video /> component
    - [ ] it should call track.mute() or track.unmute()
- [ ] Detect when a videoTrack has been muted
  - [ ] Listen for TRACK_MUTE_CHANGED (Param: JitsiTrack) OR another event that signals that someone has muted their videoTrack; expect isMuted() method to return true OR false corresponding to whatever was intended _Assuming getParticipantId()_
  - [ ] setTracks with track parameter received along with the event firing and our React app should...
  - [ ] When muted --> render a fallback view (display the participant ID) and should be (same dimensions as videoTile) when the track has been muted.
  - [ ] When unmuted --> render the video again, use track.attach again

# BUG

## Steps to reproduce

User 1 joins conference via hukev.com (app is run by `node ./server/index.js` after doing an `npm run build`)
User 2 joins conference via dev version at localhost:5000 on their machine (app can be run either with `npm start` or `node ./server/index.js`)
User 3 joins conference via dev version at localhost:5000 (OR meet.jit.si/some-default-room)
User 1 shuts off video
User 1 turns on video

## Expected Behavior

All users can see User 1 again

## Actual behavior

Only User 1 can seem themselves rendered; other users continue to see a frozen frame or nothing at all!

## Key Insights

- It is important that User 1 is the one being tested in order to reproduce the bug. This buggy behavior would not be observed if User 2 were to shut off their video and turn it back on. This also might be a good point of approach for debugging.

**Comment by khu-md** [comment]
By systematically increasing verbosity of JitsiMeetJS.logLevels from ERROR (least verbose) to WARN, we reveal the following interesting warning message (using production bundle):

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 conference.trackAdded listeners added. Use emitter.setMaxListeners() to increase limit
    at d (https://hukev.com/assets/2.78a2a46f.js:1:116167)
    at a.addListener (https://hukev.com/assets/2.78a2a46f.js:1:118449)
    at ne.on (https://hukev.com/assets/2.78a2a46f.js:15:48676)
    at https://hukev.com/assets/index.606d0a9b.js:1:8744
    at ia (https://hukev.com/assets/2.78a2a46f.js:62:83207)
    at gc (https://hukev.com/assets/2.78a2a46f.js:62:102286)
    at t.unstable_runWithPriority (https://hukev.com/assets/2.78a2a46f.js:70:3844)
    at Ji (https://hukev.com/assets/2.78a2a46f.js:62:45022)
    at mc (https://hukev.com/assets/2.78a2a46f.js:62:102045)
    at Za (https://hukev.com/assets/2.78a2a46f.js:62:93594)
    at https://hukev.com/assets/2.78a2a46f.js:62:45313
    at t.unstable_runWithPriority (https://hukev.com/assets/2.78a2a46f.js:70:3844)
    at Ji (https://hukev.com/assets/2.78a2a46f.js:62:45022)
    at qi (https://hukev.com/assets/2.78a2a46f.js:62:45258)
    at $i (https://hukev.com/assets/2.78a2a46f.js:62:45193)
    at Wa (https://hukev.com/assets/2.78a2a46f.js:62:90456)
    at ms (https://hukev.com/assets/2.78a2a46f.js:62:62273)
    at https://hukev.com/assets/index.606d0a9b.js:1:8265
    at a.<anonymous> (https://hukev.com/assets/index.606d0a9b.js:1:8607)
    at a.emit (https://hukev.com/assets/2.78a2a46f.js:1:118379)
    at https://hukev.com/assets/2.78a2a46f.js:15:57309
    at Array.forEach (<anonymous>)
    at ne.onMemberLeft (https://hukev.com/assets/2.78a2a46f.js:15:57280)
    at a.emit (https://hukev.com/assets/2.78a2a46f.js:1:118379)
    at _.onParticipantLeft (https://hukev.com/assets/2.78a2a46f.js:15:156551)
    at _.onPresenceUnavailable (https://hukev.com/assets/2.78a2a46f.js:15:157649)
    at l.onPresenceUnavailable (https://hukev.com/assets/2.78a2a46f.js:15:145723)
    at k.Handler.run (https://hukev.com/assets/2.78a2a46f.js:1:25455)
    at https://hukev.com/assets/2.78a2a46f.js:1:33893
    at Object.forEachChild (https://hukev.com/assets/2.78a2a46f.js:1:17117)
    at k.Connection._dataRecv (https://hukev.com/assets/2.78a2a46f.js:1:33742)
    at N.Websocket._onMessage (https://hukev.com/assets/2.78a2a46f.js:1:62980)


TRACE
DEBUG
INFO
LOG
WARN
ERROR
```

Until proven to be related, this is a new issue.
