### ISSUE TITLE
The vinto app occasionally becomes unresponsive

### ISSUE THREAD

**Issue by khu-md** [mohicans-pop-2008/vinto#35]
Probably. Here is the warning message received from lib-jitsi-meet. Perhaps related to our performance woes. Discovered while testing #33 . Problem with this issue is that I cannot seem to reproduce it when running the application on localhost in development mode.

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 conference.trackAdded listeners added. Use emitter.setMaxListeners() to increase limit
    at d (https://hukev.com/assets/2.78a2a46f.js:1:116167)
    at a.addListener (https://hukev.com/assets/2.78a2a46f.js:1:118449)
    at ne.on (https://hukev.com/assets/2.78a2a46f.js:15:48676)
    at https://hukev.com/assets/index.606d0a9b.js:1:8744
    at ia (https://hukev.com/assets/2.78a2a46f.js:62:83207)
    at gc (https://hukev.com/assets/2.78a2a46f.js:62:102286)
    at t.unstable_runWithPriority (https://hukev.com/assets/2.78a2a46f.js:70:3844)
    at Ji (https://hukev.com/assets/2.78a2a46f.js:62:45022)
    at mc (https://hukev.com/assets/2.78a2a46f.js:62:102045)
    at Za (https://hukev.com/assets/2.78a2a46f.js:62:93594)
    at https://hukev.com/assets/2.78a2a46f.js:62:45313
    at t.unstable_runWithPriority (https://hukev.com/assets/2.78a2a46f.js:70:3844)
    at Ji (https://hukev.com/assets/2.78a2a46f.js:62:45022)
    at qi (https://hukev.com/assets/2.78a2a46f.js:62:45258)
    at $i (https://hukev.com/assets/2.78a2a46f.js:62:45193)
    at Wa (https://hukev.com/assets/2.78a2a46f.js:62:90456)
    at ms (https://hukev.com/assets/2.78a2a46f.js:62:62273)
    at https://hukev.com/assets/index.606d0a9b.js:1:8265
    at a.<anonymous> (https://hukev.com/assets/index.606d0a9b.js:1:8607)
    at a.emit (https://hukev.com/assets/2.78a2a46f.js:1:118379)
    at https://hukev.com/assets/2.78a2a46f.js:15:57309
    at Array.forEach (<anonymous>)
    at ne.onMemberLeft (https://hukev.com/assets/2.78a2a46f.js:15:57280)
    at a.emit (https://hukev.com/assets/2.78a2a46f.js:1:118379)
    at _.onParticipantLeft (https://hukev.com/assets/2.78a2a46f.js:15:156551)
    at _.onPresenceUnavailable (https://hukev.com/assets/2.78a2a46f.js:15:157649)
    at l.onPresenceUnavailable (https://hukev.com/assets/2.78a2a46f.js:15:145723)
    at k.Handler.run (https://hukev.com/assets/2.78a2a46f.js:1:25455)
    at https://hukev.com/assets/2.78a2a46f.js:1:33893
    at Object.forEachChild (https://hukev.com/assets/2.78a2a46f.js:1:17117)
    at k.Connection._dataRecv (https://hukev.com/assets/2.78a2a46f.js:1:33742)
    at N.Websocket._onMessage (https://hukev.com/assets/2.78a2a46f.js:1:62980)
```

**Comment by khu-md** [comment]
Noticed this again - this time while running in dev mode; also conspicuously associated with whirring CPU fan.

```
webpack-internal:///./node_modules/events/events.js:46 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 conference.trackAdded listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (webpack-internal:///./node_modules/events/events.js:211:15)
    at EventEmitter.addListener (webpack-internal:///./node_modules/events/events.js:227:10)
    at JitsiConference.on (webpack-internal:///./node_modules/lib-jitsi-meet/JitsiConference.js:788:27)
    at eval (webpack-internal:///./src/App.jsx:137:16)
    at commitHookEffectListMount (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19731:26)
    at commitPassiveHookEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19769:11)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22853:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11039:10)
    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22820:12)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21737:3)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11089:24)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11039:10)
    at flushSyncCallbackQueueImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11084:7)
    at flushSyncCallbackQueue (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11072:3)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21199:9)
    at dispatchAction (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15660:5)
    at eval (webpack-internal:///./src/App.jsx:108:5)
    at EventEmitter.eval (webpack-internal:///./src/App.jsx:127:38)
    at EventEmitter.emit (webpack-internal:///./node_modules/events/events.js:158:7)
    at JitsiConference.eval (webpack-internal:///./node_modules/lib-jitsi-meet/JitsiConference.js:1821:35)
    at Array.forEach (<anonymous>)
    at JitsiConference.onRemoteTrackRemoved (webpack-internal:///./node_modules/lib-jitsi-meet/JitsiConference.js:1812:28)
    at JitsiConference._removeRemoteTracks (webpack-internal:///./node_modules/lib-jitsi-meet/JitsiConference.js:2934:14)
    at JitsiConference._removeRemoteP2PTracks (webpack-internal:///./node_modules/lib-jitsi-meet/JitsiConference.js:2918:10)
    at JitsiConference._stopP2PSession (webpack-internal:///./node_modules/lib-jitsi-meet/JitsiConference.js:3206:14)
    at JitsiConference._maybeStartOrStopP2P (webpack-internal:///./node_modules/lib-jitsi-meet/JitsiConference.js:3159:14)
    at JitsiConference.onMemberJoined (webpack-internal:///./node_modules/lib-jitsi-meet/JitsiConference.js:1554:10)
    at EventEmitter.emit (webpack-internal:///./node_modules/events/events.js:153:5)
    at ChatRoom.onPresence (webpack-internal:///./node_modules/lib-jitsi-meet/modules/xmpp/ChatRoom.js:609:35)
    at MucConnectionPlugin.onPresence (webpack-internal:///./node_modules/lib-jitsi-meet/modules/xmpp/strophe.emuc.js:114:14)
    at Strophe.Handler.run (webpack-internal:///./node_modules/strophe.js/dist/strophe.umd.js:1874:33)
    at eval (webpack-internal:///./node_modules/strophe.js/dist/strophe.umd.js:3156:35)
    at Object.forEachChild (webpack-internal:///./node_modules/strophe.js/dist/strophe.umd.js:829:21)
    at Strophe.Connection._dataRecv (webpack-internal:///./node_modules/strophe.js/dist/strophe.umd.js:3145:25)
    at Strophe$2.Websocket._onMessage (webpack-internal:///./node_modules/strophe.js/dist/strophe.umd.js:5835:28)
```

**Comment by khu-md** [comment]
This is an old bug that hasn't been able to be reproduced for a long time.
